name: ttc_exclusions
channels:
- conda-forge
dependencies:
- jupyter
- scipy
- python=3.8
- scikit-learn
- statsmodels
- sqlalchemy
- matplotlib
- numpy
- pandas
- seaborn
- jupyterlab
- pymongo
- rdkit
- umap-learn
- plotly=5.3.1
- bokeh
- ipykernel
- pip
- pip:
  - openpyxl
  - dash
  - jupyter-dash
